name: Bug report
description: File a bug report
labels: [bug, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file this bug report.
  - type: textarea
    attributes:
      label: Bug description
      description: A clear and concise description of the bug.
      value: |
        <!--
          What did you do? (Provide reproduction code in next section)

          What did you expect to happen?

          What happened instead?

          Do you have an error stack-trace or screenshots?
        -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: |
        Provide a _minimal_ reproduction of the problem for us to debug.

        The smaller the reproduction, the faster we can debug and resolve your issue.
        Please do your best to eliminate all unnecessary code and dependencies to boil it down to bare minimums.

        ⚠️ If a reproduction is not provided, the issue will be closed.
      value: |
        <!--
          Provide a minimal reproduction in one of the following forms:
            1. One small code-snippet we can copy-paste [no dependencies allowed]
            2. Link to a repository with the command to run in the package.json script `start`
            3. Pull request with a failing test-case [no dependencies allowed]

          Remove as much irrelevant code to make it easier for others to read and debug.
          This includes unnecessary files, dependencies, properties in package.json, tsconfig.json, etc.
        -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Describe the environment the issue is happening in. This information is used to for reproduction and debugging.
      value: |
        <!--
          Run and paste the output of:
          ```
          npx envinfo --system --npmPackages tsx --binaries
          ```
        -->

        System:
          OS:
          CPU:
          Shell:
        Binaries:
          Node:
          npm:
        npmPackages:
          tsx:
      render: shell
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Can you contribute a fix?
      description: We would love it if you can open a pull request to fix this bug!
      options:
        - label: I’m interested in opening a pull request for this issue.
