name: 🐛 Bug report
description: Run into a bug? File a report and get the help you need!
labels: [bug, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        > 💁‍♂️ Keep in mind this is a collaborative effort. Please do your best to debug, communicate, and demonstrate the problem.

  - type: checkboxes
    attributes:
      label: Precheck
      description: Before starting the issue, please make sure you agree to the following.
      options:
        - label: I searched existing issues before opening this one to avoid duplicates
          required: true

        - label: I'm able to reproduce this issue and prove it with a minimal reproduction
          required: true

        - label: I understand this is not a place to ask for free debugging support
          required: true

  - type: markdown
    attributes:
      value: |
        ## 👀 Tell us about the bug
        A _clear and concise_ description of what the bug is.

  - type: textarea
    attributes:
      label: Problem
      description: Please refrain from describing anything other than the problem.
      placeholder: |
        What's the problem?
        Do you have an error stack trace?
        Do you have screenshots?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: |
        What did you expect to happen?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📋 Minimal reproduction
        > ⚠️ If a **minimal** reproduction is not provided, **the issue will be closed & locked.**

        The minimal reproduction proves a bug exists in this project, allows others to debug it for you, and streamlines resolution.

        <details>
          <summary><strong>How do I create a minimal reproduction?</strong></summary>

        1. Delete all unnecessary files and data. Keep it under 10 files.

            Delete irrelevant files (e.g. `LICENSE`, `.npmrc`, `.github`).
            Do you have unnecessary dependencies, scripts, properties in `package.json`?

        2. Delete all unnecessary code. Reduce the scope.

            Try to narrow the scope of the reproduction as much as possible.
            Is it a frontend or backend problem? Delete the other.
            Is it a TypeScript problem? Try converting to JavaScript to see if it still exists.
            Ideally, the code is reduced to a few lines of code in a single file.

        3. Set the `start` script in `package.json` to the command that demonstrates the bug.

        4. Verify the reproduction.

            Try running it yourself, and check:
            - Is the problem immediately reproducible?
            - Are dependencies properly declared?
            - Could I find more files or code that isn't necessary?

        5. Upload the reproduction to [StackBlitz](https://stackblitz.com), or a new GitHub repository, so it can be opened in the browser.
        </details>

        Starter template: [fork this template on StackBlitz](https://stackblitz.com/edit/node-huzszn?file=index.ts)

        The _smaller_ the reproduction, the _faster_ others can help you.

  - type: input
    attributes:
      label: Minimal reproduction URL
      placeholder: https://stackblitz.com/edit/...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        > **🙋 Need help?**
        >
        > Get personalized help through my [_Priority Support_ service](https://github.com/sponsors/privatenumber).
        > From minimal reproduction creation to debugging, I'm happy to assist you!

  - type: markdown
    attributes:
      value: "## 🌍 Environment"

  - type: input
    attributes:
      label: Version
      placeholder: v0.0.0
    validations:
      required: true

  - type: input
    attributes:
      label: Node.js version
      placeholder: v0.0.0
    validations:
      required: true

  - type: dropdown
    id: package-manager
    attributes:
      label: Package manager
      options:
        - npm
        - yarn
        - pnpm
        - bun
        - N/A
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Operating system
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 🛠️ Contribute
        It would be amazing if you can contribute to the project! This project is open source, free to use, and maintained by volunteers. This could be a great opportunity to give back and improve the project for everyone, including yourself.

  - type: checkboxes
    attributes:
      label: Contributions
      options:
        - label: I plan to open a pull request for this issue
        - label: I plan to make a financial contribution to this project

  - type: markdown
    attributes:
      value: |
        ## 🚀 Need immediate attention?
        Escalate this issue by becoming a [_Priority Patron_ sponsor](https://github.com/sponsors/privatenumber)! As a _Priority Patron_, your concern will receive prompt attention, ensuring faster and more efficient resolution.

        [👉 Become a _Priority Patron_ now!](https://github.com/sponsors/privatenumber)
