name: Bug report
description: File a bug report
labels: [bug, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file this bug report.
  - type: textarea
    attributes:
      label: Bug description
      description: A clear and concise description of the bug.
      value: |
        <!--
          What did you do? (Provide reproduction code in next section)

          What did you expect to happen?

          What happened instead?

          Do you have an error stack-trace or screenshots?
        -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: |
        Provide a minimal reproduction in one of the following forms:
          1. Small code-snippet (no more than one) we can copy-paste <kbd>No dependencies allowed</kbd>
          2. Pull request with a failing test-case <kbd>No dependencies allowed</kbd>
          3. Link to a repository containing minimal reproduction <kbd>Dependencies allowed</kbd>
            - Fork [this template on StackBlitz](https://stackblitz.com/edit/node-huzszn?file=index.ts)
            - Set the command to run in the `package.json` script `start`
            - 👉 **Tip:** The _smaller_ the reproduction, the _faster_ we can debug and resolve your issue
              - Remove all unnecessary files, code, & dependencies. This is the first step of debugging so doing this will save us work.
              - If possible, convert TypeScript to plain JavaScript to eliminate the possibility of it being a TS bug

        ⚠️ If a _minimal_ reproduction is not provided, the issue will be closed
      placeholder: Reproduction snippet, link, or pull-request
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Run and paste the output of:
        ```
        npx envinfo --system --npmPackages tsx --binaries
        ```
        
        This information is used to for reproduction and debugging.
      placeholder: |
        System:
          OS:
          CPU:
          Shell:
        Binaries:
          Node:
          npm:
        npmPackages:
          tsx:
      render: shell
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Can you work on a fix?
      description: We would love for you to contribute!
      options:
        - label: I’m interested in opening a pull request to address this issue.
