name: 🐛 Bug report
description: Run into a bug? File a report and get the help you need!
labels: [bug, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        > 💁‍♂️ Keep in mind this is a collaborative effort. Please do your best to debug, communicate, and demonstrate the problem.

  - type: checkboxes
    attributes:
      label: Acknowledgements
      description: Before starting the issue, please make sure you agree to the following.
      options:
        - label: I searched existing issues before opening this one to avoid duplicates
          required: true

        - label: I understand this is not a place for seek help, but to report a bug
          required: true

        - label: I understand that the bug must be proven first with a minimal reproduction
          required: true

        - label: I will be polite, respectful, and considerate of people's time and effort
          required: true

  - type: markdown
    attributes:
      value: |
        ## 📋 Minimal reproduction
        > ⚠️ **Issue closure warning**: Without a minimal reproduction URL, your issue will be closed & locked without response.

        The minimal reproduction is the core of your issue. Most times, this is all we look at to understand the problem.

        When we debug your reproduction, we start by removing everything unncessary. Including converting TypeScript to JavaScript where possible, and removing _all_ unnecessary files & code (especially inside `node_modules`).
        Minimizing the scope of the problem helps reveal the root cause.

        <details>
            <summary><strong>Guidelines for creating a Minimal Reproduction</strong></summary>

        1. **Eliminate extra files**: Limit to under 10 files. Discard non-essential files (like `LICENSE`, `.npmrc`, `.github`) and trim extraneous properties from `package.json`.

        2. **Concentrate on the Issue**: Focus solely on the bug. Exclude unrelated frontend/backend components. If it's a TypeScript issue, convert to JavaScript for clarity. Aim for minimal lines of code in a single file.

        3. **Configure 'start' script**: In `package.json`, ensure the `start` script clearly demonstrates the bug.

        4. **Thorough verification**: Test the reproduction yourself. Confirm immediate reproducibility, proper dependency declarations, and absence of redundant code or files. This mirrors the maintainers' process of scrutinizing every aspect.

        5. **Upload**: Share your minimal reproduction on [StackBlitz](https://stackblitz.com) or a new GitHub repository, ensuring it's accessible via a browser.

        </details>

        **Starter Template**: [Fork this StackBlitz template](https://stackblitz.com/edit/node-huzszn?file=index.ts)

        The more refined and concise your reproduction, the faster and more effectively maintainers can address your issue.

  - type: input
    attributes:
      label: Minimal reproduction URL
      placeholder: https://stackblitz.com/edit/...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        > **🙋 Need help?**
        >
        > Get personalized help through my [_Priority Support_ service](https://github.com/sponsors/privatenumber).
        > From minimal reproduction creation to debugging, I'm happy to assist you!

  - type: markdown
    attributes:
      value: "## 🌍 Environment"

  - type: input
    attributes:
      label: Version
      placeholder: v0.0.0
    validations:
      required: true

  - type: input
    attributes:
      label: Node.js version
      placeholder: v0.0.0
    validations:
      required: true

  - type: dropdown
    id: package-manager
    attributes:
      label: Package manager
      options:
        - npm
        - yarn
        - pnpm
        - bun
        - N/A
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Operating system
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 🗒️ Extra information

        This section is for complex issues that require further explaining.

        Please focus more on minimizing the reproduction to get to the core of the issue. Usually, that's all we need to look at.

  - type: textarea
    attributes:
      label: Problem & Expected behavior
      value: |
        Under 200 words:
        - What happened?
        - What did you expect instead?
        - Do you have an error stack trace?
        - Do you have documentation links?
        - Do you have screenshots?

  - type: markdown
    attributes:
      value: |
        ## 🛠️ Contribute
        It would be amazing if you can contribute to the project! This project is open source, free to use, and maintained by volunteers. This could be a great opportunity to give back and improve the project for everyone, including yourself.

  - type: checkboxes
    attributes:
      label: Contributions
      options:
        - label: I plan to open a pull request for this issue
        - label: I plan to make a financial contribution to this project

  - type: markdown
    attributes:
      value: |
        ## 🚀 Need immediate attention?
        Escalate this issue by becoming a [_Priority Patron_ sponsor](https://github.com/sponsors/privatenumber)! As a _Priority Patron_, your concern will receive prompt attention, ensuring faster and more efficient resolution.

        [👉 Become a _Priority Patron_ now!](https://github.com/sponsors/privatenumber)
