blank_issues_enabled: false
contact_links:
  - name: 💬 Help / Questions / Discussions
    url: https://github.com/privatenumber/tsx/discussions
    about: Use GitHub Discussions for anything else

  - name: 🚀 Priority Support
    url: https://github.com/sponsors/privatenumber/
    about: Need help? Get prioritized help for all your questions and issues
