name: 🌟 Feature request
description: Have a great idea for this project? Tell us more!
labels: [enhancement, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        > 💁‍♂️ Please remember others are volunteering to help you for free, and put in your best effort to follow this form.

        ## 👀 Tell us about your idea

  - type: textarea
    attributes:
      label: Feature request
      description: A clear and concise description of the feature.
      placeholder: |
        I would love to be able to...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivations
      description: |
        Describe the problem you’re tackling with this feature request.
      placeholder: |
        How did you come across this idea?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: |
        Have you considered alternative solutions? Is there a workaround?
      placeholder: |
        Do you have alternative proposals?

        Are there workarounds?

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Anything else to share? Screenshots? Links?

  - type: markdown
    attributes:
      value: |
        > **🙋 Experiencing a challenging problem and need expert assistance?**
        >
        > Get personalized help through my [_Priority Support_ service](https://github.com/sponsors/privatenumber). From debugging to implementation, I'm here to assist you!

  - type: markdown
    attributes:
      value: |
        ## 🛠️ Contribute
        It would be amazing if you can contribute to the project! This project is open source, free to use, and maintained by volunteers. This could be a great opportunity to give back and improve the project for everyone, including yourself.

  - type: checkboxes
    attributes:
      label: Contributions
      options:
        - label: I plan to open a pull request for this issue
        - label: I plan to make a financial contribution to this project

  - type: markdown
    attributes:
      value: |
        ## 🚀 Need immediate attention?
        Escalate this issue by becoming a [_Priority Patron_ sponsor](https://github.com/sponsors/privatenumber)! As a _Priority Patron_, your concern will receive prompt attention, ensuring faster and more efficient resolution.

        [👉 Become a _Priority Patron_ now!](https://github.com/sponsors/privatenumber)
