import type { NodeError } from '../types.js';

// Symbol marker to prevent double enhancement (survives error re-throws)
const tsxEnhancedSymbol = Symbol.for('tsx-enhanced-module-error');

type EnhancedError = NodeError & {
	[key: symbol]: boolean;
};

/**
 * Enhances a MODULE_NOT_FOUND or ERR_MODULE_NOT_FOUND error with information
 * about the paths that were searched. This helps users debug why tsx
 * couldn't find their module.
 */
export const enhanceModuleError = (
	error: NodeError,
	triedPaths: string[],
): NodeError => {
	const enhancedError = error as EnhancedError;

	if (
		triedPaths.length === 0
		|| (error.code !== 'MODULE_NOT_FOUND' && error.code !== 'ERR_MODULE_NOT_FOUND')
		// Don't enhance if already enhanced
		|| enhancedError[tsxEnhancedSymbol]
	) {
		return error;
	}

	// Mark as enhanced
	enhancedError[tsxEnhancedSymbol] = true;

	const searchPathsInfo = `\n\ntsx searched the following paths:\n${
		triedPaths.map(p => `  - ${p}`).join('\n')
	}`;

	// Only modify the message - the stack will be regenerated by Node when printed
	error.message += searchPathsInfo;

	return error;
};
