name: Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Get Node.js cache directory
        id: node-cache
        shell: bash
        run: echo "path=$(node -p 'require("cachedir")("nve")')" >> $GITHUB_OUTPUT

      - name: Cache Node.js versions
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ${{ steps.node-cache.outputs.path }}
          key: ${{ runner.os }}-nodejs-${{ hashFiles('.nvmrc') }}-${{ hashFiles('tests/utils/node-versions.ts') }}
          restore-keys: ${{ runner.os }}-nodejs-

      - name: Test
        run: pnpm test

      - name: Type check
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pnpm type-check

      - name: Lint
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pnpm lint
